name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [ push ]
jobs:
  Show-Python_version:
    runs-on: ubuntu-latest
    steps:
      - run: python --version

  Test-Code-With-Pylint:
    runs-on: ubuntu-latest
    steps:
      - run: pip install pylint
      - run: git clone https://github.com/mbabiak39/cw_praca_z_kodem
      - run: cd cw_praca_z_kodem
      - run: find . -name '*.py' -exec pylint {} \;
