name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [ push ]
jobs:
  Show-Python_version:
    runs-on: ubuntu-latest
    steps:
      - run: python --version

  Test-Code-With-Pylint:
    runs-on: ubuntu-latest
    steps:
      - run: pip install pylint
      - run: cd ..
      - run: ls -lsa
      - run: pylint -v app.py
